import type { Message } from "@bufbuild/protobuf";
import type { GenMessage } from "@bufbuild/protobuf/codegenv2";
import {
	ClientBoundCombined,
	CPacketAnimation,
	CPacketBlockAction,
	CPacketBlockUpdate,
	CPacketChangeServers,
	CPacketCloseWindow,
	CPacketConfirmTransaction,
	CPacketDestroyEntities,
	CPacketDisconnect,
	CPacketEntityAction,
	CPacketEntityAttach,
	CPacketEntityEffect,
	CPacketEntityEquipment,
	CPacketEntityMetadata,
	CPacketEntityPositionAndRotation,
	CPacketEntityProperties,
	CPacketEntityRelativePositionAndRotation,
	CPacketEntityStatus,
	CPacketEntityVelocity,
	CPacketExplosion,
	CPacketJoinGame,
	CPacketLeaderboard,
	CPacketLocalStorage,
	CPacketMessage,
	CPacketOpenShop,
	CPacketOpenWindow,
	CPacketParticles,
	CPacketPlayerList,
	CPacketPlayerPosition,
	CPacketPlayerPosLook,
	CPacketPlayerReconciliation,
	CPacketPong,
	CPacketQueueNext,
	CPacketRemoveEntityEffect,
	CPacketRespawn,
	CPacketScoreboard,
	CPacketServerInfo,
	CPacketServerMetadata,
	CPacketSetExperience,
	CPacketSetSlot,
	CPacketShopProperties,
	CPacketSignEditorOpen,
	CPacketSoundEffect,
	CPacketSpawnEntity,
	CPacketSpawnExperienceOrb,
	CPacketSpawnPlayer,
	CPacketTabComplete,
	CPacketTimeUpdate,
	CPacketTitle,
	CPacketUpdate,
	CPacketUpdateCommandBlock,
	CPacketUpdateHealth,
	CPacketUpdateLeaderboard,
	CPacketUpdateScoreboard,
	CPacketUpdateSign,
	CPacketUpdateStatus,
	CPacketUseBed,
	CPacketWindowItems,
	CPacketWindowProperty,
	SPacketAdminAction,
	SPacketAnalytics,
	SPacketBreakBlock,
	SPacketClick,
	SPacketClickWindow,
	SPacketCloseWindow,
	SPacketConfirmTransaction,
	SPacketCraftItem,
	SPacketEnchantItem,
	SPacketEntityAction,
	SPacketHeldItemChange,
	SPacketLoginStart,
	SPacketMessage,
	SPacketOpenShop,
	SPacketPing,
	SPacketPlaceBlock,
	SPacketPlayerAbilities,
	SPacketPlayerAction,
	SPacketPlayerInput,
	SPacketPlayerPosLook,
	SPacketQueueNext,
	SPacketRequestChunk,
	SPacketRespawn,
	SPacketTabComplete,
	SPacketUpdateCommandBlock,
	SPacketUpdateInventory,
	SPacketUpdateSign,
	SPacketUseEntity,
	SPacketUseItem,
} from "../../gen/protocol2_pb";
import { CPacketChunkData } from "../../gen/protocol3_pb";

export const CPACKET_MAP = {
	CPacketAnimation,
	CPacketBlockAction,
	CPacketBlockUpdate,
	CPacketChangeServers,
	CPacketChunkData,
	CPacketCloseWindow,
	CPacketConfirmTransaction,
	CPacketDestroyEntities,
	CPacketDisconnect,
	CPacketEntityAction,
	CPacketEntityEquipment,
	CPacketEntityMetadata,
	CPacketEntityPositionAndRotation,
	CPacketEntityRelativePositionAndRotation,
	CPacketEntityStatus,
	CPacketEntityVelocity,
	CPacketExplosion,
	CPacketJoinGame,
	CPacketLeaderboard,
	CPacketLocalStorage,
	CPacketMessage,
	CPacketOpenWindow,
	CPacketParticles,
	CPacketPlayerList,
	CPacketPlayerPosition,
	CPacketPlayerPosLook,
	CPacketPlayerReconciliation,
	CPacketPong,
	CPacketRespawn,
	CPacketScoreboard,
	CPacketServerInfo,
	CPacketSetSlot,
	CPacketSignEditorOpen,
	CPacketSoundEffect,
	CPacketSpawnEntity,
	CPacketSpawnPlayer,
	CPacketTabComplete,
	CPacketTitle,
	CPacketUpdate,
	CPacketUpdateHealth,
	CPacketUpdateLeaderboard,
	CPacketUpdateScoreboard,
	CPacketUpdateSign,
	CPacketUpdateStatus,
	CPacketWindowItems,
	CPacketWindowProperty,
	CPacketUseBed,
	CPacketQueueNext,
	CPacketSpawnExperienceOrb,
	CPacketSetExperience,
	CPacketOpenShop,
	CPacketShopProperties,
	CPacketEntityProperties,
	CPacketEntityEffect,
	CPacketRemoveEntityEffect,
	CPacketUpdateCommandBlock,
	CPacketEntityAttach,
	CPacketServerMetadata,
	CPacketTimeUpdate,
	ClientBoundCombined,
};
export const SPACKET_MAP = {
	SPacketAdminAction,
	SPacketAnalytics,
	SPacketClickWindow,
	SPacketCloseWindow,
	SPacketConfirmTransaction,
	SPacketEnchantItem,
	SPacketEntityAction,
	SPacketHeldItemChange,
	SPacketLoginStart,
	SPacketMessage,
	SPacketOpenShop,
	SPacketPing,
	SPacketPlayerAbilities,
	SPacketPlayerAction,
	SPacketPlayerPosLook,
	SPacketRespawn,
	SPacketTabComplete: SPacketTabComplete,
	SPacketUpdateSign,
	SPacketUseEntity,
	SPacketUpdateCommandBlock,
	SPacketQueueNext,
	SPacketPlayerInput,
	SPacketBreakBlock,
	SPacketClick,
	SPacketCraftItem,
	SPacketPlaceBlock,
	SPacketRequestChunk,
	SPacketUpdateInventory,
	SPacketUseItem,
};

export const NAME_TO_ID: Record<string, number> = {};
export const ID_TO_PACKET: Record<string, typeof Message> = {};
export const ID_TO_NAME: Record<number, string> = {};

let currentId = 0;
for (const [i, v] of Object.entries(CPACKET_MAP)) {
	NAME_TO_ID[i] = currentId;
	ID_TO_PACKET[currentId] = v;
	ID_TO_NAME[currentId] = i;
	currentId++;
}
for (const [i, v] of Object.entries(SPACKET_MAP)) {
	NAME_TO_ID[i] = currentId;
	ID_TO_PACKET[currentId] = v;
	ID_TO_NAME[currentId] = i;
	currentId++;
}

console.log(Object.fromEntries(Object.entries(ID_TO_PACKET).map(([a, b]) => [a, b?.name])));
